
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - todo-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true # React development mode ke liye zaroori hai
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge